# Informações sobre a base de dados

Este arquivo contém dados abrangentes do programa de fidelidade da companhia aérea, abrangendo a campanha promocional, inclui detalhes sobre inscrição no programa, cancelamentos e informações adicionais do cliente.



A companhia aérea implementou uma campanha promocional, com o objetivo de potenciar a adesão ao programa. O conjunto de dados abrange informações sobre inscrições, inscrições, cancelamentos no programa de fidelidade e dados demográficos complementares dos clientes.

# Fazendo consultas SQL - para extrair os dados
### Notas de Estudo

In [ ]:
#importando bibliotecas e conectando o banco de dados
import sqlite3 as sl3
import pandas as pd
#usar comando conn da biblioteca sqlite para conectar com o banco de dados
conn = sl3.connect("database.db")

In [ ]:
#consulta dos dados no banco de dados
consulta_atividade= "SELECT * FROM flight_activity LIMIT 10"
df_atividade = pd.read_sql_query(consulta_atividade, conn)

In [ ]:
#fechando a conexão com o banco de dados
# conn.close()

In [ ]:
df_atividade.head()

,loyalty_number,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0
2,100140,2017,1,6,0,6,1200,120.0,0,0
3,100214,2017,1,0,0,0,0,0.0,0,0
4,100272,2017,1,0,0,0,0,0.0,0,0

# Juntando duas tabelas

existem vários tipos de união, iremos usar o LEFT JOIN

In [ ]:

consulta_atividade = """

  SELECT
    A.coluna1,
    A.coluna2,
    B.coluna1,
    B.coluna2

  FROM
    tabela A  LEFT JOIN tabela B ON (A.coluna3 = B.coluna3) //coluna 3 é a coluna comum nas duas tabelas

  WHERE
  A.coluna1 > 1000


 """

In [ ]:
consulta_atividade = """

  SELECT
    *
  FROM flight_activity

 """
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

,loyalty_number,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0
2,100140,2017,1,6,0,6,1200,120.0,0,0
3,100214,2017,1,0,0,0,0,0.0,0,0
4,100272,2017,1,0,0,0,0,0.0,0,0

## Verificando qual coluna da tabela flight_activity é comum na tabela light_loyalty_history

In [ ]:
consulta_atividade = """

  SELECT
    *
  FROM flight_loyalty_history

 """
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN

In [ ]:
df_atividade.columns

Index(['loyalty_number', 'country', 'province', 'city', 'postal_code',
       'gender', 'education', 'salary', 'marital_status', 'loyalty_card',
       'clv', 'enrollment_type', 'enrollment_year', 'enrollment_month',
       'cancellation_year', 'cancellation_month'],
      dtype='object')

A coluna comum nas duas tabelas é a 	loyalty_number

In [ ]:
consulta_atividade = """

  SELECT
    *
  FROM flight_activity fa LEFT JOIN flight_loyalty_history flh ON (fa.loyalty_number = flh.loyalty_number)

 """
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

,loyalty_number,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed,...,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month
0,100018,2017,1,3,0,3,1521,152.0,0,0,...,Bachelor,92552.0,Married,Aurora,7919.20,Standard,2016,8,NaN,NaN
1,100102,2017,1,10,4,14,2030,203.0,0,0,...,College,NaN,Single,Nova,2887.74,Standard,2013,3,NaN,NaN
2,100140,2017,1,6,0,6,1200,120.0,0,0,...,College,NaN,Divorced,Nova,2838.07,Standard,2016,7,NaN,NaN
3,100214,2017,1,0,0,0,0,0.0,0,0,...,Bachelor,63253.0,Married,Star,4170.57,Standard,2015,8,NaN,NaN
4,100272,2017,1,0,0,0,0,0.0,0,0,...,Bachelor,91163.0,Divorced,Star,6622.05,Standard,2014,1,NaN,NaN

# Salvando o arquivo com as duas tabelas juntas

In [ ]:
df_atividade.columns

Index(['loyalty_number', 'year', 'month', 'flights_booked',
       'flights_with_companions', 'total_flights', 'distance',
       'points_accumulated', 'points_redeemed', 'dollar_cost_points_redeemed',
       'loyalty_number', 'country', 'province', 'city', 'postal_code',
       'gender', 'education', 'salary', 'marital_status', 'loyalty_card',
       'clv', 'enrollment_type', 'enrollment_year', 'enrollment_month',
       'cancellation_year', 'cancellation_month'],
      dtype='object')

In [ ]:
df_atividade.to_csv('atividade_tratada.csv')

# Inspecionando os dados com o Python

In [ ]:
df_atividade.head()

,loyalty_number,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed,...,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month
0,100018,2017,1,3,0,3,1521,152.0,0,0,...,Bachelor,92552.0,Married,Aurora,7919.20,Standard,2016,8,NaN,NaN
1,100102,2017,1,10,4,14,2030,203.0,0,0,...,College,NaN,Single,Nova,2887.74,Standard,2013,3,NaN,NaN
2,100140,2017,1,6,0,6,1200,120.0,0,0,...,College,NaN,Divorced,Nova,2838.07,Standard,2016,7,NaN,NaN
3,100214,2017,1,0,0,0,0,0.0,0,0,...,Bachelor,63253.0,Married,Star,4170.57,Standard,2015,8,NaN,NaN
4,100272,2017,1,0,0,0,0,0.0,0,0,...,Bachelor,91163.0,Divorced,Star,6622.05,Standard,2014,1,NaN,NaN

In [ ]:
df_atividade.shape

(405624, 26)

In [ ]:
df_atividade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405624 entries, 0 to 405623
Data columns (total 26 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loyalty_number               405624 non-null  int64
 1   year                         405624 non-null  int64
 2   month                        405624 non-null  int64
 3   flights_booked               405624 non-null  int64
 4   flights_with_companions      405624 non-null  int64
 5   total_flights                405624 non-null  int64
 6   distance                     405624 non-null  int64
 7   points_accumulated           405624 non-null  float64
 8   points_redeemed              405624 non-null  int64
 9   dollar_cost_points_redeemed  405624 non-null  int64
 10  loyalty_number               405624 non-null  int64
 11  country                      405624 non-null  object
 12  province                     405624 non-null  object
 13  city                         405624 non-null  object
 14  postal_code                  405624 non-null  object
 15  gender                       405624 non-null  object
 16  education                    405624 non-null  object
 17  salary                       302952 non-null  float64
 18  marital_status               405624 non-null  object
 19  loyalty_card                 405624 non-null  object
 20  clv                          405624 non-null  float64
 21  enrollment_type              405624 non-null  object
 22  enrollment_year              405624 non-null  int64
 23  enrollment_month             405624 non-null  int64
 24  cancellation_year            50064 non-null   float64
 25  cancellation_month           50064 non-null   float64
dtypes: float64(5), int64(12), object(9)
memory usage: 80.5+ MB

As colunas salary, cancellation_year, cancellation_month, estão com dados faltantes

# Verificando quais são os dados nulos no banco de dados

In [ ]:
#saber quantos valores faltantes há em cada coluna
df_atividade.isna().sum()

loyalty_number                      0
year                                0
month                               0
flights_booked                      0
flights_with_companions             0
total_flights                       0
distance                            0
points_accumulated                  0
points_redeemed                     0
dollar_cost_points_redeemed         0
loyalty_number                      0
country                             0
province                            0
city                                0
postal_code                         0
gender                              0
education                           0
salary                         102672
marital_status                      0
loyalty_card                        0
clv                                 0
enrollment_type                     0
enrollment_year                     0
enrollment_month                    0
cancellation_year              355560
cancellation_month             355560
dtype: int64

# Exercícios

1. Selecionar os números do cartão de fidelidade dos passeiros, a cidade e o gênero, dos passageiros que tem o
cartão Star de fidelidade, mas nunca realizaram nenhuma viagem de avião ( Dica: “loyalty_card” = “Star” e “distance” = 0 )

In [ ]:
consulta_atividade = """

  SELECT
    fa.loyalty_number,
    flh.city,
    flh.gender,
    flh.loyalty_card

  FROM
    flight_activity fa LEFT JOIN flight_loyalty_history flh ON (fa.loyalty_number = flh.loyalty_number)
  WHERE
    flh.loyalty_card = 'Star' AND fa.distance = 0

"""
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

   loyalty_number      city  gender loyalty_card
0          480934   Toronto  Female         Star
1          480934   Toronto  Female         Star
2          480934   Toronto  Female         Star
3          480934   Toronto  Female         Star
4          549612  Edmonton    Male         Star

2. Selecionar os números do cartão de fidelidade, o gênero e a cidade de todos os passageiros do sexo feminino que
moram na cidade de Toronto, fizeram mais de 30 viagens no total e tem o cartão de fidelidade do tipo Aurora.

In [ ]:
consulta_atividade = """

  SELECT
    fa.loyalty_number,
    flh.city,
    flh.gender,
    flh.loyalty_card,
    fa.total_flights


  FROM
    flight_activity fa LEFT JOIN flight_loyalty_history flh ON (fa.loyalty_number = flh.loyalty_number)

  WHERE
  flh.gender = 'Female' AND flh.city= 'Toronto' AND fa.total_flights = 30 AND flh.loyalty_card = 'Aurora'


"""
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

   loyalty_number     city  gender loyalty_card  total_flights
0          896861  Toronto  Female       Aurora             30
1          442792  Toronto  Female       Aurora             30
2          856496  Toronto  Female       Aurora             30
3          615411  Toronto  Female       Aurora             30

3. Selecionar os números do cartão de fidelidade, o tipo do cartão, o genero e os pontos acumulados, dos passageiros
com salário acima de 13200, estado civil como casado e nível acadêmico como mestrado e número de voos
agendados igual ao número total de voos.

In [ ]:
consulta_atividade = """

  SELECT
    fa.loyalty_number,
    flh.loyalty_card,
    flh.gender,
    flh.city,
    fa.points_accumulated

  FROM
    flight_activity fa LEFT JOIN flight_loyalty_history flh ON (fa.loyalty_number = flh.loyalty_number)

  WHERE
    flh.salary > 13200
    AND flh.marital_status = 'Married'
    AND flh.education = 'Master'
    AND fa.flights_booked = fa.total_flights


"""
df_atividade = pd.read_sql_query(consulta_atividade, conn)
df_atividade.head()

   loyalty_number loyalty_card gender     city  points_accumulated
0          205785         Star   Male  Toronto                 0.0
1          205785         Star   Male  Toronto                 0.0
2          205785         Star   Male  Toronto                 0.0
3          205785         Star   Male  Toronto                 0.0
4          205785         Star   Male  Toronto                 0.0

# Analisando o arquivo com as duas tabelas juntas

In [ ]:
from google.colab import drive

In [ ]:
#Extraindo o arquivo tratado do google drive
drive.mount('/content/drive')
path = "/content/atividade_tratada.csv"
df_tratado = pd.read_csv(path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

4. Qual o salário médio dos passageiros?

In [ ]:
salario_medio = df_tratado['salary'].mean()
salario_medio

79268.82595262615

5. Qual o valor da soma total da distância percorrida pelos voos registrados na planilha de dados.?

In [ ]:
distancia_total = df_tratado['distance'].sum()
distancia_total

490350765

6. Qual o valor total de pontos acumulados?

In [ ]:
pontos_acumulados = df_tratado['points_accumulated'].sum()
pontos_acumulados

50172736.25

7. Qual o maior salário?

In [ ]:
maior_salario = df_tratado.loc[:, 'salary'].max()
maior_salario

407228.0

8. Qual o menor salário?

In [ ]:
menor_salario = df_tratado.loc[:, 'salary'].min()
menor_salario

-58486.0